# Generated by Django 3.1.2 on 2020-10-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('voyages', '0002_auto_20201027_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accueil', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('presentation', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('politesse', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('sourire', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('professionnelle', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('nbr_passages', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('speech_de_depart', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('speech_controles_police', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('speech_entree_ville', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('speech_pointes_arrets', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('speech_bilingue', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('odeur', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('nettoyage_final', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], max_length=1)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='clients.client')),
                ('voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyage', to='voyages.voyage')),
            ],
            options={
                'ordering': ['voyage__date_voyage'],
            },
        ),
    ]
