# Generated by Django 3.1.2 on 2020-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='accueil',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='nbr_passages',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='nettoyage_final',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='odeur',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='politesse',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='presentation',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='professionnelle',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='sourire',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='speech_bilingue',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='speech_controles_police',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='speech_de_depart',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='speech_entree_ville',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='speech_pointes_arrets',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('A', 'Abstention')], default=('A', 'Abstention'), max_length=1),
        ),
    ]
