# Generated by Django 3.1.2 on 2020-11-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_auto_20201030_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquete',
            old_name='speech_pointes_arrets',
            new_name='speech_points_arrets',
        ),
    ]
