# Generated by Django 3.1.2 on 2020-10-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0001_initial'),
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voyage', models.DateTimeField()),
                ('destination', models.CharField(choices=[('D', 'Douala'), ('Y', 'Yaounde')], max_length=1)),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur', to='employes.employe')),
                ('hotesse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotesse', to='employes.employe')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['date_voyage'],
            },
        ),
    ]
