# Generated by Django 3.1.2 on 2020-10-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
        ('vehicules', '0001_initial'),
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voyages',
            new_name='Voyage',
        ),
    ]
