# Generated by Django 3.1.2 on 2020-11-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_auto_20201027_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='billet_gratuit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='consomation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='voyage',
            name='prix',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
