# Generated by Django 3.1.2 on 2020-11-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_auto_20201113_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='consomation',
            new_name='consommation',
        ),
    ]
