# Generated by Django 3.1.2 on 2020-11-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0005_auto_20201113_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='nbr_de_places',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
