# Generated by Django 3.1.2 on 2020-11-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0006_voyage_nbr_de_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='revenus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
