# Generated by Django 3.1.2 on 2020-11-14 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_auto_20201113_1144'),
        ('voyages', '0007_voyage_revenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='chauffeur',
            field=models.ForeignKey(limit_choices_to={'poste': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur', to='employes.employe'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='hotesse',
            field=models.ForeignKey(limit_choices_to={'poste': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotesse', to='employes.employe'),
        ),
    ]
