# Generated by Django 3.1.2 on 2020-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
