# Generated by Django 3.1.2 on 2020-10-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='sieges',
            field=models.IntegerField(),
        ),
    ]
