# Generated by Django 3.1.2 on 2020-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_auto_20201027_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='type_de_voiture',
            field=models.CharField(choices=[('B', 'Bus'), ('P', 'Personnel'), ('G', 'Groupe')], default='B', max_length=1),
        ),
    ]
