# Generated by Django 3.1.2 on 2020-11-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0005_vehicule_dateheure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateheure', models.DateTimeField()),
                ('consommation', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('immatriculation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['dateheure'],
            },
        ),
    ]
